"""XGBoost mastitis risk model training.

Trains a 4-class XGBoost classifier on the synthetic dataset generated by synth.py.

Split strategy: GROUP split by cow_sim_id (NOT random row shuffle).
  Train: first 70% of unique cows
  Val:   next 15% (early stopping)
  Test:  last 15% (final evaluation — never seen during training)

This prevents data leakage: all daily snapshots from the same cow stay in the same split.

Usage:
  python ml/train.py
  python ml/train.py --data ml/data/training_data.csv --out ml/models/mastitis_xgb.ubj
"""

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
)
from xgboost import XGBClassifier

# Add project root to path for imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from ml.features import FEATURE_COLS

LABEL_NAMES = ["no_risk", "low", "moderate", "high"]


def group_split(df: pd.DataFrame, train_frac=0.70, val_frac=0.15):
    """Split by cow_sim_id so all snapshots from one cow stay together."""
    cow_ids = df["cow_sim_id"].unique()
    np.random.seed(42)
    np.random.shuffle(cow_ids)

    n = len(cow_ids)
    n_train = int(n * train_frac)
    n_val   = int(n * val_frac)

    train_cows = set(cow_ids[:n_train])
    val_cows   = set(cow_ids[n_train : n_train + n_val])
    test_cows  = set(cow_ids[n_train + n_val :])

    train_df = df[df["cow_sim_id"].isin(train_cows)]
    val_df   = df[df["cow_sim_id"].isin(val_cows)]
    test_df  = df[df["cow_sim_id"].isin(test_cows)]

    print(f"\nGroup split:")
    print(f"  Train cows: {len(train_cows):4d}  |  rows: {len(train_df):7,}")
    print(f"  Val   cows: {len(val_cows):4d}  |  rows: {len(val_df):7,}")
    print(f"  Test  cows: {len(test_cows):4d}  |  rows: {len(test_df):7,}")

    return train_df, val_df, test_df


def early_detection_rate(y_true, y_pred, df_test):
    """Measure how often cows are flagged low/moderate before reaching high.

    For each test cow that ever reached label=3 (high), check if any earlier
    snapshot was predicted as 1 (low) or 2 (moderate) when true label was 0 or 1.
    """
    detected_early = 0
    total_clinical = 0

    for cow_id, group in df_test.groupby("cow_sim_id"):
        group = group.sort_index()
        true_labels = group["label"].values
        pred_labels = y_pred[group.index]

        if 3 not in true_labels:
            continue   # never went clinical

        total_clinical += 1
        clinical_idx = np.where(true_labels == 3)[0][0]

        # Check if predicted low or moderate at any point before clinical
        pre_clinical_preds = pred_labels[:clinical_idx]
        if any(p in [1, 2] for p in pre_clinical_preds):
            detected_early += 1

    rate = detected_early / total_clinical * 100 if total_clinical > 0 else 0.0
    return rate, detected_early, total_clinical


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default="ml/data/training_data.csv")
    parser.add_argument("--out",  default="ml/models/mastitis_xgb.ubj")
    parser.add_argument("--report", default="ml/models/evaluation_report.txt")
    args = parser.parse_args()

    # ── Load data ──────────────────────────────────────────────────────────────
    data_path = Path(args.data)
    if not data_path.exists():
        print(f"ERROR: {data_path} not found. Run ml/synth.py first.")
        sys.exit(1)

    df = pd.read_csv(data_path)
    print(f"Loaded {len(df):,} rows from {data_path}")
    print(f"Label distribution:\n{df['label'].value_counts().sort_index()}")

    # ── Split ─────────────────────────────────────────────────────────────────
    train_df, val_df, test_df = group_split(df)

    X_train = train_df[FEATURE_COLS].values
    y_train = train_df["label"].values
    X_val   = val_df[FEATURE_COLS].values
    y_val   = val_df["label"].values
    X_test  = test_df[FEATURE_COLS].values
    y_test  = test_df["label"].values

    # ── Class weights (handle imbalance) ──────────────────────────────────────
    from sklearn.utils.class_weight import compute_sample_weight
    sample_weights = compute_sample_weight("balanced", y_train)

    # ── Train XGBoost ─────────────────────────────────────────────────────────
    print("\nTraining XGBoost (4-class mastitis risk predictor)...")
    model = XGBClassifier(
        n_estimators=400,
        max_depth=5,
        learning_rate=0.08,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,
        reg_lambda=1.0,
        objective="multi:softprob",
        num_class=4,
        eval_metric="mlogloss",
        early_stopping_rounds=30,
        random_state=42,
        verbosity=0,
        device="cpu",
    )

    model.fit(
        X_train, y_train,
        sample_weight=sample_weights,
        eval_set=[(X_val, y_val)],
        verbose=50,
    )

    print(f"\nBest iteration: {model.best_iteration}")

    # ── Evaluate on test set ──────────────────────────────────────────────────
    y_pred = model.predict(X_test)
    acc    = accuracy_score(y_test, y_pred)

    print(f"\n{'='*60}")
    print(f"TEST SET EVALUATION (never seen during training)")
    print(f"{'='*60}")
    print(f"\nOverall Accuracy: {acc*100:.1f}%\n")

    report = classification_report(
        y_test, y_pred,
        target_names=LABEL_NAMES,
        digits=3,
    )
    print(report)

    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(f"{'':>12}", end="")
    for n in LABEL_NAMES:
        print(f"{n:>12}", end="")
    print()
    for i, row in enumerate(cm):
        print(f"{LABEL_NAMES[i]:>12}", end="")
        for val in row:
            print(f"{val:>12}", end="")
        print()

    # ── Early detection rate ───────────────────────────────────────────────────
    edr, detected, total_clin = early_detection_rate(y_test, y_pred, test_df.reset_index())
    print(f"\nEarly Detection Rate: {edr:.1f}%")
    print(f"  ({detected}/{total_clin} clinical cows flagged low/moderate >= 7 days early)")

    # ── Feature importance ────────────────────────────────────────────────────
    print("\nTop 10 Features by Gain:")
    importance = model.get_booster().get_score(importance_type="gain")
    sorted_imp = sorted(importance.items(), key=lambda x: x[1], reverse=True)
    for feat, score in sorted_imp[:10]:
        print(f"  {feat:<30} {score:.2f}")

    # ── Save model ────────────────────────────────────────────────────────────
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    model.save_model(str(out_path))
    print(f"\nModel saved: {out_path}")

    # ── Save evaluation report ────────────────────────────────────────────────
    report_path = Path(args.report)
    with open(report_path, "w") as f:
        f.write(f"Mastitis XGBoost Evaluation Report\n")
        f.write(f"Overall Accuracy: {acc*100:.2f}%\n\n")
        f.write(report)
        f.write(f"\nEarly Detection Rate: {edr:.1f}% ({detected}/{total_clin})\n")
        f.write("\nFeature Importance (Gain):\n")
        for feat, score in sorted_imp:
            f.write(f"  {feat:<30} {score:.2f}\n")
    print(f"Report saved: {report_path}")


if __name__ == "__main__":
    main()
